

services:
  squid:
    image: ubuntu/squid:6.6-24.04_beta
    restart: unless-stopped
    environment:
      TZ: "Asia/Tokyo"
    volumes: []
    # networks:
    #   infra1_net:
    #     ipv4_address: 10.10.20.2


  docker-registry:
    image: registry:2
    restart: unless-stopped
    volumes: []
    # networks:
    #   infra1_net:
    #     ipv4_address: 10.10.20.3

networks:
  infra1_net:
    external: true
  #   driver: ipvlan
  #   driver_opts:
  #     parent: eth0
  #   ipam:
  #     config:
  #       - subnet: 10.10.20.0/24
  #         gateway: 10.10.20.1

# create the network with the following command:
# docker network create --driver ipvlan -o parent=eth0 --gateway 172.16.0.1 --subnet 172.16.0.0/24 service1_net