

services:
  squid:
    image: ubuntu/squid:6.6-24.04_beta
    # restart: unless-stopped
    restart: no
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./squid/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./squid:/etc/squid:ro
      - squid_spool:/var/spool/squid
      - squid_cache:/var/cache/squid
    ports:
      - "3128:3128"
    # networks:
    #   infra1_net:
    #     ipv4_address: 10.10.20.2


  # docker-registry:
  #   image: registry:2
  #   restart: unless-stopped
  #   volumes: []
  #   # networks:
  #   #   infra1_net:
  #   #     ipv4_address: 10.10.20.3


volumes:
  squid_spool:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /srv/squid
  #     o: bind
  squid_cache:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /srv/squid/cache
    #   o: bind

  # docker_registry_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /srv/docker-registry
  #     o: bind


networks:
  infra1_net:
    external: true
  #   driver: ipvlan
  #   driver_opts:
  #     parent: eth0
  #   ipam:
  #     config:
  #       - subnet: 10.10.20.0/24
  #         gateway: 10.10.20.1

# create the network with the following command:
# docker network create --driver ipvlan -o parent=eth0 --gateway 172.16.0.1 --subnet 172.16.0.0/24 service1_net