
SRC_DIR := src
SRC_YML := $(wildcard $(SRC_DIR)/*.yml)

ALL := compose.yml compose-ipvlan.yml

COMOPSE_HEADER := \#\n\# Do not edit this file directly. It is generated by Makefile.\n\#
COMPOSE_OPTIONS := --no-interpolate --no-path-resolution --no-normalize --no-env-resolution

.PHONY: all clean

all: $(ALL)

clean:
	@echo "Cleaning the project..."
	rm -f $(ALL)

compose.yml: $(SRC_YML)
	@echo "$(COMOPSE_HEADER)" > $@
	docker compose -f src/base.yml -f src/network-bridge.yml config $(COMPOSE_OPTIONS) >> $@

compose-ipvlan.yml: $(SRC_YML)
	@echo "$(COMOPSE_HEADER)" > $@
	docker compose -f src/base.yml -f src/network-ipvlan.yml config $(COMPOSE_OPTIONS) >> $@



