#!/bin/bash

echo "Generating compose files..."

OPTIONS="--no-interpolate --no-path-resolution --no-normalize --no-env-resolution"
# --variables"

echo -e "#\n# Do not edit this file directly. It is generated by merge.sh.\n#" > compose.yml
docker compose -f src/base.yml -f src/network-bridge.yml config ${OPTIONS} >> compose.yml

echo -e "#\n# Do not edit this file directly. It is generated by merge.sh.\n#" > compose-ipvlan.yml
#docker compose -f src/base.yml -f src/ipvlan-network.yml config --no-interpolate > compose-ipvlan.yml
docker compose -f src/base.yml -f src/network-ipvlan.yml config ${OPTIONS} >> compose-ipvlan.yml