

services:
  squid:
    image: ubuntu/squid:6.6-24.04_beta
    # restart: unless-stopped
    restart: ${RESTART:-no}
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ./squid/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./squid:/etc/squid:ro
      - squid_spool:/var/spool/squid
      - squid_cache:/var/cache/squid

volumes:
  squid_spool:
  squid_cache: