

services:
  squid:
    image: ${SQUID_IMAGE:-tetsuyainfra/compose-squid:latest}
    restart: ${RESTART:-unless-stopped}
    environment:
      TZ: ${TZ:-UTC}
      CACHE_DIR: ${CACHE_DIR:-ufs /var/cache/squid 10000 16 256}
      MAXIMUM_OBJECT_SIZE: ${MAXIMUM_OBJECT_SIZE:-512 MB}
      CACHE_MEM: ${CACHE_MEM:-256 MB}
    volumes:
      - squid_spool:/var/spool/squid
      - squid_cache:/var/cache/squid

volumes:
  squid_spool:
  squid_cache: